doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        logging: true
        profiling: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

            DentalOfficeUserBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/lib/DentalOffice/UserBundle/src/Domain/Entity'
                prefix: 'DentalOffice\UserBundle\Domain\Entity'
                alias: DentalOfficeUserBundle

            DentalOfficePatientBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/lib/DentalOffice/PatientBundle/src/Domain/Entity'
                prefix: 'DentalOffice\PatientBundle\Domain\Entity'
                alias: DentalOfficePatientBundle

            DentalOfficeMedicalRecordBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/lib/DentalOffice/MedicalRecordBundle/src/Domain/Entity'
                prefix: 'DentalOffice\MedicalRecordBundle\Domain\Entity'
                alias: DentalOfficeMedicalRecordBundle

            DentalOfficeAppointmentSchedulingBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/lib/DentalOffice/AppointmentSchedulingBundle/src/Domain/Entity'
                prefix: 'DentalOffice\AppointmentSchedulingBundle\Domain\Entity'
                alias: DentalOfficeDentalAppointmentSchedulingBundle

            DentalOfficePaymentsBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/lib/DentalOffice/PaymentsBundle/src/Domain/Entity'
                prefix: 'DentalOffice\PaymentsBundle\Domain\Entity'
                alias: DentalOfficePaymentsBundle

            DentalOfficeInvoiceBundle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/lib/DentalOffice/InvoiceBundle/src/Domain/Entity'
                prefix: 'DentalOffice\InvoiceBundle\Domain\Entity'
                alias: DentalOfficeInvoiceBundle
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            #dbname_suffix: '_test%env(default::TEST_TOKEN)%'
            logging: true

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
